//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoListApplication.DataModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Gorevlers = new HashSet<Gorevler>();
        }
    
        public int id { get; set; }
        public string adi_soyadi { get; set; }
        public Nullable<int> depatman_id { get; set; }
        public Nullable<bool> aktif { get; set; }
        public Nullable<bool> silindi { get; set; }
        public Nullable<System.DateTime> olusturulma_zamani { get; set; }
        public string olusturan_kullanici { get; set; }
        public Nullable<System.DateTime> guncelleme_zamani { get; set; }
        public string guncelleyen_kullanici { get; set; }
        public Nullable<bool> departman_yoneticisi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Gorevler> Gorevlers { get; set; }
    }
}
